version: "3.8"

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: canon-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/canon123
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./neo4j-seed.cypher:/var/lib/neo4j/import/seed.cypher
    networks:
      - canon-network

  redis:
    image: redis:7-alpine
    container_name: canon-redis
    ports:
      - "6379:6379"
    networks:
      - canon-network

  langflow:
    image: langflowai/langflow:latest
    container_name: canon-langflow
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///./langflow.db
    networks:
      - canon-network

  bff:
    build:
      context: ./apps/bff
      dockerfile: Dockerfile
    container_name: canon-bff
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=canon123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LANGFLOW_API_KEY=${LANGFLOW_API_KEY}
      - LANGFLOW_BASE_URL=${LANGFLOW_BASE_URL:-http://langflow:7860}
      - LANGFLOW_FLOW_ID=${LANGFLOW_FLOW_ID}
    depends_on:
      - neo4j
      - redis
      - langflow
    networks:
      - canon-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: canon-web
    ports:
      - "8080:80"
    environment:
      - BFF_URL=http://bff:3000
    volumes:
      - ./apps/web/public:/usr/share/nginx/html:ro
    depends_on:
      - bff
    networks:
      - canon-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  canon-network:
    driver: bridge
